// dummy data

export const Featured = [
  {
    id: 'e1',
    category: 'wicket keeper',
    player: 'K.Rahul',
    point: 9.5,
    team: 'ind',
  },
  {
    id: 'e2',
    category: 'wicket keeper',
    player: 'R.Pant',
    point: 9,
    team: 'ind',
  },
  {
    id: 'e3',
    category: 'wicket keeper',
    player: 'J.Braistow',
    point: 8.5,
    team: 'eng',
  },
  {
    id: 'e4',
    category: 'batsmen',
    player: 'V.Kohli',
    point: 9.5,
    team: 'ind',
  },
  {
    id: 'e5',
    category: 'batsmen',
    player: 'R.Sharma',
    point: 9.5,
    team: 'ind',
  },
  {
    id: 'e6',
    category: 'batsmen',
    player: 'D.Malan',
    point: 9.5,
    team: 'eng',
  },
  {
    id: 'e7',
    category: 'batsmen',
    player: 'J.Root',
    point: 9.0,
    team: 'eng',
  },
  {
    id: 'e8',
    category: 'batsmen',
    player: 'E.Morgon',
    point: 8.0,
    team: 'eng',
  },

  {
    id: 'e9',
    category: 'batsmen',
    player: 'Sk Yadav',
    point: 8.0,
    team: 'ind',
  },
  {
    id: 'e10',
    category: 'batsmen',
    player: 'Ishan Kishan',
    point: 7.5,
    team: 'ind',
  },
  {
    id: 'e11',
    category: 'batsmen',
    player: 'J.Butler',
    point: 8.5,
    team: 'eng',
  },
  {
    id: 'e12',
    category: 'all-rounder',
    player: 'R.Jadeja',
    point: 8.5,
    team: 'ind',
  },
  {
    id: 'e13',
    category: 'all-rounder',
    player: 'M.Ali',
    point: 8.5,
    team: 'eng',
  },
  {
    id: 'e14',
    category: 'all-rounder',
    player: 'R.Ashwin',
    point: 8.5,
    team: 'ind',
  },
  {
    id: 'e15',
    category: 'all-rounder',
    player: 'S.Curran',
    point: 8.0,
    team: 'eng',
  },
  {
    id: 'e25',
    category: 'all-rounder',
    player: 'H.Pandya',
    point: 8.0,
    team: 'ind',
  },
  {
    id: 'e16',
    category: 'all-rounder',
    player: 'A.Patel',
    point: 8.0,
    team: 'ind',
  },
  {
    id: 'e17',
    category: 'bowler',
    player: 'T.Curran',
    point: 8.0,
    team: 'eng',
  },
  {
    id: 'e18',
    category: 'bowler',
    player: 'Chris Woakes',
    point: 8.5,
    team: 'eng',
  },
  {
    id: 'e19',
    category: 'bowler',
    player: 'J. Bumrah',
    point: 9.0,
    team: 'ind',
  },
  {
    id: 'e20',
    category: 'bowler',
    player: 'Md.Shami',
    point: 8.5,
    team: 'ind',
  },
  {
    id: 'e21',
    category: 'bowler',
    player: 'M.Wood',
    point: 8.5,
    team: 'eng',
  },
  {
    id: 'e22',
    category: 'bowler',
    player: 'A.Rashid',
    point: 8.0,
    team: 'eng',
  },
  {
    id: 'e23',
    category: 'bowler',
    player: 'D.Chahar',
    point: 8.0,
    team: 'ind',
  },
  {
    id: 'e24',
    category: 'bowler',
    player: 'J.Archer',
    point: 8.5,
    team: 'eng',
  },
];
